// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import routeProps from './routeProps';

if (process.env.NODE_ENV === 'development') {
  Object.entries(routeProps).forEach(([key, value]) => {
    const internalProps = ['path', 'id', 'parentId', 'isLayout', 'isWrapper', 'layout', 'clientLoader'];
    Object.keys(value).forEach((prop) => {
      if (internalProps.includes(prop)) {
        throw new Error(
          `[UmiJS] route '${key}' should not have '${prop}' prop, please remove this property in 'routeProps'.`
        )
      }
    })
  })
}

import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","title":"首页","parentId":"@@/global-layout","id":"1"},"2":{"path":"/demo/:id","title":"测试页","parentId":"@@/global-layout","id":"2"},"3":{"path":"/personal","title":"个人中心","parentId":"@@/global-layout","id":"3"},"4":{"path":"/personal","redirect":"/personal/order","parentId":"3","id":"4"},"5":{"path":"/personal/order","title":"订单页","parentId":"3","id":"5"},"6":{"path":"/personal/profile","title":"订单页","parentId":"3","id":"6"},"7":{"path":"*","title":"404","parentId":"@@/global-layout","id":"7"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__index" */'@/pages/index.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__demo" */'@/pages/demo.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__personal" */'@/pages/personal.tsx')),
'4': React.lazy(() => import( './EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__personal__order" */'@/pages/personal/order.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__personal__profile" */'@/pages/personal/profile.tsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'G:/learn/react/react-systematic/umidemo/src/layouts/index.tsx')),
},
  };
}
