export default class Constants {
  /**
   * label font weight 400.
   */
  static readonly LABEL_FONT_WEIGHT: number = 400;

  /**
   * title font weight 500.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * course item padding 12.
   */
  static readonly COURSE_ITEM_PADDING: number = 12;

  /**
   * loading duration 2000.
   */
  static readonly LOADING_DURATION: number = 2000;

  /**
   * title line number 2.
   */
  static readonly TITLE_LINE_NUMBER: number = 2;

  /**
   * 100 percent.
   */
  static readonly FULL_PERCENT: string = '100%';

  /**
   * classify title percent.
   */
  static readonly CLASSIFY_TITLE_PERCENT: string = '55%';
}
