export { createVNode, Fragment, Text } from './createVNode'
export { h } from './h'
export { createRenderer } from './renderer'
export { getCurrentInstance, setCurrentInstance } from './component'
export * from './apiLifeCycle'
export * from './apiInject'
export { defineAsyncComponent } from './defineAsyncComponent'

export * from '@vue/reactivity'
export * from './keepAlive'
